/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SluzbyWebovaAnalytikaRouteImport } from './routes/sluzby/webova-analytika'
import { Route as SluzbyVyvojWebuRouteImport } from './routes/sluzby/vyvoj-webu'
import { Route as SluzbyVylepseniSeoRouteImport } from './routes/sluzby/vylepseni-seo'
import { Route as SluzbyRedesignRouteImport } from './routes/sluzby/redesign'
import { Route as SluzbyOptimalizaceWebuRouteImport } from './routes/sluzby/optimalizace-webu'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SluzbyWebovaAnalytikaRoute = SluzbyWebovaAnalytikaRouteImport.update({
  id: '/sluzby/webova-analytika',
  path: '/sluzby/webova-analytika',
  getParentRoute: () => rootRouteImport,
} as any)
const SluzbyVyvojWebuRoute = SluzbyVyvojWebuRouteImport.update({
  id: '/sluzby/vyvoj-webu',
  path: '/sluzby/vyvoj-webu',
  getParentRoute: () => rootRouteImport,
} as any)
const SluzbyVylepseniSeoRoute = SluzbyVylepseniSeoRouteImport.update({
  id: '/sluzby/vylepseni-seo',
  path: '/sluzby/vylepseni-seo',
  getParentRoute: () => rootRouteImport,
} as any)
const SluzbyRedesignRoute = SluzbyRedesignRouteImport.update({
  id: '/sluzby/redesign',
  path: '/sluzby/redesign',
  getParentRoute: () => rootRouteImport,
} as any)
const SluzbyOptimalizaceWebuRoute = SluzbyOptimalizaceWebuRouteImport.update({
  id: '/sluzby/optimalizace-webu',
  path: '/sluzby/optimalizace-webu',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/profil': typeof ProfilRoute
  '/terms': typeof TermsRoute
  '/sluzby/optimalizace-webu': typeof SluzbyOptimalizaceWebuRoute
  '/sluzby/redesign': typeof SluzbyRedesignRoute
  '/sluzby/vylepseni-seo': typeof SluzbyVylepseniSeoRoute
  '/sluzby/vyvoj-webu': typeof SluzbyVyvojWebuRoute
  '/sluzby/webova-analytika': typeof SluzbyWebovaAnalytikaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/profil': typeof ProfilRoute
  '/terms': typeof TermsRoute
  '/sluzby/optimalizace-webu': typeof SluzbyOptimalizaceWebuRoute
  '/sluzby/redesign': typeof SluzbyRedesignRoute
  '/sluzby/vylepseni-seo': typeof SluzbyVylepseniSeoRoute
  '/sluzby/vyvoj-webu': typeof SluzbyVyvojWebuRoute
  '/sluzby/webova-analytika': typeof SluzbyWebovaAnalytikaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/profil': typeof ProfilRoute
  '/terms': typeof TermsRoute
  '/sluzby/optimalizace-webu': typeof SluzbyOptimalizaceWebuRoute
  '/sluzby/redesign': typeof SluzbyRedesignRoute
  '/sluzby/vylepseni-seo': typeof SluzbyVylepseniSeoRoute
  '/sluzby/vyvoj-webu': typeof SluzbyVyvojWebuRoute
  '/sluzby/webova-analytika': typeof SluzbyWebovaAnalytikaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/faq'
    | '/privacy'
    | '/profil'
    | '/terms'
    | '/sluzby/optimalizace-webu'
    | '/sluzby/redesign'
    | '/sluzby/vylepseni-seo'
    | '/sluzby/vyvoj-webu'
    | '/sluzby/webova-analytika'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/faq'
    | '/privacy'
    | '/profil'
    | '/terms'
    | '/sluzby/optimalizace-webu'
    | '/sluzby/redesign'
    | '/sluzby/vylepseni-seo'
    | '/sluzby/vyvoj-webu'
    | '/sluzby/webova-analytika'
  id:
    | '__root__'
    | '/'
    | '/faq'
    | '/privacy'
    | '/profil'
    | '/terms'
    | '/sluzby/optimalizace-webu'
    | '/sluzby/redesign'
    | '/sluzby/vylepseni-seo'
    | '/sluzby/vyvoj-webu'
    | '/sluzby/webova-analytika'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FaqRoute: typeof FaqRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfilRoute: typeof ProfilRoute
  TermsRoute: typeof TermsRoute
  SluzbyOptimalizaceWebuRoute: typeof SluzbyOptimalizaceWebuRoute
  SluzbyRedesignRoute: typeof SluzbyRedesignRoute
  SluzbyVylepseniSeoRoute: typeof SluzbyVylepseniSeoRoute
  SluzbyVyvojWebuRoute: typeof SluzbyVyvojWebuRoute
  SluzbyWebovaAnalytikaRoute: typeof SluzbyWebovaAnalytikaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sluzby/webova-analytika': {
      id: '/sluzby/webova-analytika'
      path: '/sluzby/webova-analytika'
      fullPath: '/sluzby/webova-analytika'
      preLoaderRoute: typeof SluzbyWebovaAnalytikaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sluzby/vyvoj-webu': {
      id: '/sluzby/vyvoj-webu'
      path: '/sluzby/vyvoj-webu'
      fullPath: '/sluzby/vyvoj-webu'
      preLoaderRoute: typeof SluzbyVyvojWebuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sluzby/vylepseni-seo': {
      id: '/sluzby/vylepseni-seo'
      path: '/sluzby/vylepseni-seo'
      fullPath: '/sluzby/vylepseni-seo'
      preLoaderRoute: typeof SluzbyVylepseniSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sluzby/redesign': {
      id: '/sluzby/redesign'
      path: '/sluzby/redesign'
      fullPath: '/sluzby/redesign'
      preLoaderRoute: typeof SluzbyRedesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sluzby/optimalizace-webu': {
      id: '/sluzby/optimalizace-webu'
      path: '/sluzby/optimalizace-webu'
      fullPath: '/sluzby/optimalizace-webu'
      preLoaderRoute: typeof SluzbyOptimalizaceWebuRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FaqRoute: FaqRoute,
  PrivacyRoute: PrivacyRoute,
  ProfilRoute: ProfilRoute,
  TermsRoute: TermsRoute,
  SluzbyOptimalizaceWebuRoute: SluzbyOptimalizaceWebuRoute,
  SluzbyRedesignRoute: SluzbyRedesignRoute,
  SluzbyVylepseniSeoRoute: SluzbyVylepseniSeoRoute,
  SluzbyVyvojWebuRoute: SluzbyVyvojWebuRoute,
  SluzbyWebovaAnalytikaRoute: SluzbyWebovaAnalytikaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
